#!/usr/bin/env python3
"""
normalise/semgrep_adapter.py

Semgrep -> the unified finding schema (docs/adr/0018). This is the exact
trap DESIGN.md's "severity normalisation contract" warned about, and it
was confirmed live rather than assumed: Semgrep's own JSON output
(extra.severity) only ever holds ERROR / WARNING / INFO -- a three-level
scale, not a CVSS-mapped Critical/High/Medium/Low one. There is no
"Critical" tier to reach for.

Checked, and rejected, an alternative before settling on this mapping:
extra.metadata's impact/likelihood/confidence fields exist, but are
noisy in practice -- confirmed live against a real subprocess-shell-true
(OS command injection) finding, which reported impact="LOW" despite
being a genuinely serious bug. Deriving severity from those fields would
have been a false precision worse than not having it. Semgrep's own
top-level severity verdict is used instead, mapped 1:1, nothing cleverer
layered on top.

Documented limitation, stated plainly rather than hidden: a Semgrep
finding can never be normalized to "critical" through this mapping. If
a specific rule ever needs to be treated as Critical, that requires an
explicit rule_id override list -- not built here, tracked as a
follow-up, not silently assumed solved.

Also confirmed live: extra.fingerprint is not usable -- it is gated
behind Semgrep Registry login and its actual value in an anonymous run
is the literal string "requires login", not a real identifier. This
adapter constructs its own fingerprint instead:
{check_id}:{path}:{start_line}, stable across runs on unchanged code,
which is exactly the property a fingerprint needs for the differential-
gating work this schema exists to eventually support.

CRITICAL correction, found live during SADR-0024/0025 verification: the
`path` Semgrep reports depends entirely on how it was invoked, NOT on
where the file actually lives -- confirmed directly, scanning identical
content two ways: `semgrep ... /src` (an absolute target, what
scripts/generate-baseline.py and gate-bundle/run-pilot-bundle.py both
pass) returns `path: "/src/app.py"`; `semgrep ... .` (the fast gate's own
target, pipelines/fast.woodpecker.yml) returns `path: "app.py"`. Building
the fingerprint from that raw path meant the SAME finding produced THREE
different fingerprints depending only on which of the three scan sites
ran it -- a baseline entry generated by generate-baseline.py (absolute
`/src/...` paths) could never match what the fast gate computes for the
identical file (bare relative paths) on every single PR. Every Semgrep
finding baselined at onboarding still blocked afterward; only Trivy
findings (whose `Target` field is already scan-root-relative regardless
of invocation form) happened to survive this bug undetected.

Fixed by normalizing every path to be relative to an explicit `root`
before it ever reaches the fingerprint. Callers whose scan target was an
absolute path (or a container-internal mount point) pass that same value
as `root`; the fast gate, which already scans "." and therefore already
gets relative paths back, passes none. This makes the fingerprint
identical across every scan site regardless of invocation form -- the
actual property differential gating needs, not merely "looks stable in
one fixture."

Usage: python3 semgrep_adapter.py <semgrep-report.json>
Reads Semgrep's native --json output (NOT --sarif -- SARIF's `level`
field collapses even Semgrep's own three levels further, per DESIGN.md's
own warning; the native JSON is the more informative source and this
adapter's whole job is recovering severity, so it uses the richer input).
"""
import json
import os
import posixpath
import sys

SEVERITY_MAP = {
    "ERROR": "high",
    "WARNING": "medium",
    "INFO": "low",
}


def normalize(semgrep_results, root=None):
    out = []
    for r in semgrep_results:
        raw_severity = r["extra"]["severity"]
        check_id = r["check_id"]
        path = r["path"]
        # posixpath, not os.path: Semgrep's own `path` field is always a
        # POSIX-style path (it only ever runs inside Linux containers, in
        # every real invocation site) -- using os.path here would make
        # this stripping silently do nothing whenever the ADAPTER itself
        # happens to run on Windows (found live: os.path.isabs("/src/x")
        # is False under ntpath, since it has no drive letter, so the
        # os.path version of this guard never fired during Windows-side
        # unit testing even though it needs to fire in every real, always-
        # Linux, production invocation). Only ever strips an absolute path
        # down to scan-root-relative -- never touches an already-relative
        # path (the fast gate's own "." target already returns these).
        if root and posixpath.isabs(path):
            path = posixpath.relpath(path, root)
        line = r["start"]["line"]
        out.append({
            "tool": "semgrep",
            "rule_id": check_id,
            "severity": SEVERITY_MAP.get(raw_severity, "low"),
            "file": path,
            "line": line,
            "message": r["extra"].get("message", check_id),
            "fingerprint": f"{check_id}:{path}:{line}",
            "raw_severity": raw_severity,
        })
    return out


def main():
    if len(sys.argv) not in (2, 3):
        print("usage: semgrep_adapter.py <semgrep-report.json> [scan-root]", file=sys.stderr)
        return 2

    path = sys.argv[1]
    root = sys.argv[2] if len(sys.argv) == 3 else None
    if not os.path.exists(path):
        print(json.dumps([]))
        return 0

    with open(path) as fh:
        data = json.load(fh)

    print(json.dumps(normalize(data.get("results", []), root)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
